### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by dxcore35** [AtilioA/web-scraping-for-sentence-mining#7]
Can you please provide simple example of the output?

**Comment by AtilioA** [comment]
I'm assuming you're talking about the `reverso_scraping/` directory? The other directories refer to Brazilian websites (except for ` csv_to_wavenet/` which is kind of a personal script).

**Comment by dxcore35** [comment]
Ou aI see! Yes it was for "reverso_scraping" script 🙏🏻

**Comment by AtilioA** [comment]
Sure, I'll provide some examples whenever I have some spare time.

**Comment by dxcore35** [comment]
🙏🏻

**Comment by AtilioA** [comment]
Commit 5cd2d2bd025af04ac2def0a87617970e63b46012 should add sufficient instructions on how to scrap and generate data. Let me know if you need further help.

**Comment by AtilioA** [comment]
Commit 5cd2d2bd025af04ac2def0a87617970e63b46012 should add sufficient instructions on how to scrap and generate data. Let me know if you need further help.

**Comment by jaysta** [comment]
> 🙏🏻
> [dxcore35](https://github.com/dxcore35)
hello, I'm try to reach out to you here. Could you please leave a way for me to contact you or could you contact  me at my discord:
precursor#4574
many thanks.
